//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GP_Report_Request.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class accident_requests
    {
        public int id { get; set; }
        public Nullable<int> driver_id { get; set; }
        public decimal latitude { get; set; }
        public decimal longitude { get; set; }
        public string address { get; set; }
        public int area_id { get; set; }
        public System.DateTime time { get; set; }
    
        public virtual area_range area_range { get; set; }
        public virtual user user { get; set; }
    }
}
