//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GP_Report_Request.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class area_range
    {
        public area_range()
        {
            this.accident_requests = new HashSet<accident_requests>();
            this.real_accident = new HashSet<real_accident>();
        }
    
        public int area_id { get; set; }
        public int country_id { get; set; }
        public int city_id { get; set; }
        public decimal max_latitude { get; set; }
        public decimal min_latitude { get; set; }
        public decimal max_longitude { get; set; }
        public decimal min_longitude { get; set; }
        public System.DateTime time { get; set; }
    
        public virtual ICollection<accident_requests> accident_requests { get; set; }
        public virtual city city { get; set; }
        public virtual country country { get; set; }
        public virtual ICollection<real_accident> real_accident { get; set; }
    }
}
