//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GP_Report_Request.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public user()
        {
            this.accident_requests = new HashSet<accident_requests>();
        }
    
        public int driver_id { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string email { get; set; }
        public string alternative_email { get; set; }
        public string user_name { get; set; }
        public int country_id { get; set; }
        public Nullable<int> city_id { get; set; }
        public string phone { get; set; }
        public Nullable<System.DateTime> birth_date { get; set; }
        public Nullable<int> gender_id { get; set; }
        public System.DateTime signup_date { get; set; }
        public Nullable<System.DateTime> last_modified { get; set; }
    
        public virtual ICollection<accident_requests> accident_requests { get; set; }
        public virtual city city { get; set; }
        public virtual country country { get; set; }
    }
}
